server:
  port: 8501

spring:
  application:
    name: eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://test.tembin.com:8501/eureka/
    register-with-eureka: false
    fetch-registry: false
