server:
  port: 8502
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8501/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: config-server
  cloud:
    config:
      name: config-server
      label: master
      server:
        git:
          uri: https://github.com/lkx1993/spring-cloud-config.git
          #username:
          #password: